#!/bin/bash

# Synopsys
#   test_one <file>
#
# Description
#   Test one file.
#   Check whether output of compression = input of extraction.
#   Check whether input of compression = output of extraction.
#
# Options
#   file
#     Filename without extension and directory.
#     E.g. pnp
#
# Exit Status
#   0 Test passed.
#   1 Error occurred.

print_usage() {
    echo "Usage:"
    echo "  test_one <file>"
}

# Go to directory of script.
cd "${BASH_SOURCE%/*}" || { echo "Error: Cannot go to script dir."; exit 1; }

# Check argument.
[ "$#" = "1" ] || { echo "Error: File missing."; print_usage; exit 1; }

[ ! -f "$1" ] || { echo "Error: File doest not exist."; exit 1; }

# Start validating.
echo "Validating $1..."

../../bin/compress -m w -c ../inputs/$1.txt ../outputs/$1.lzw > temp1.txt \
    || { echo "Error: Compression failed."; exit 1; }

../../bin/compress -m w -x ../outputs/$1.lzw{,.out} > temp2.txt \
    || { echo "Error: Extraction failed."; exit 1; }


if [ "$(diff -q <(head -n -4 temp1.txt) <(head -n -1 temp2.txt))" != "" ]; then
    echo "Error: Output of compression != input of extraction."; 
    read -p "View file? (y/n): " ans
    [ "$ans" = y ] && vimdiff temp{1,2}.txt
    rm temp{1,2}.txt
    exit 1;
fi

rm temp{1,2}.txt

if [ "$(diff -q ../inputs/$1.txt ../outputs/$1.lzw.out)" != "" ]; then
    echo "Error: Input of compression != Output of extraction.";
    read -p "View file? (y/n): " ans
    [ "$ans" = y ] && vimdiff ../inputs/$1.txt ../outputs/$1.lzw.out
    exit 1
fi

echo "Passed."
